# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v2

      - name: Deploy dbt models
        run: |
          cd /home/emilegill743/Projects/dbt_models
          git fetch --all
          git reset --hard origin/master
          
